spring:
  profiles:
    active: local
  application:
    name: yu-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: 123456
  # session配置
  session:
    store-type: redis
    # session 30天过期
    timeout: 2592000
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 604800
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yupi.yuaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
